# -*- coding: utf-8 -*-
"""
Phase‑Aware Scattering‑Inspired Encoder–Decoders: Loss Base
=========================================================

This module defines the abstract foundation for all objective functions used 
within the project. It ensures a consistent interface for loss computation, 
weighting, and integration into the training pipeline.
"""

# -------------------------------------------------------------------------------------------------------------------

# Importing Global Libraries
from __future__ import annotations

import logging

import torch.nn as nn

from typing import List
from abc import ABC, abstractmethod

# Import custom libraries

# -------------------------------------------------------------------------------------------------------------------

# ---------------------------------------------------------------------
# LOGGERS
# ---------------------------------------------------------------------

debug_logger = logging.getLogger(f"{__name__.split('.')[0]}.debug")
semantic_logger = logging.getLogger(f"{__name__.split('.')[0]}.semantic")

# -------------------------------------------------------------------------------------------------------------------

# ---------------------------------------------------------------------
# IMPLEMENTATION
# ---------------------------------------------------------------------

# == BaseLoss ==
class BaseLoss(nn.Module, ABC):
    """
    Abstract base class for all loss implementations.

    This class enforces a uniform interface for all objectives, facilitating 
    the handling of loss weighting and reduction strategies across different 
    training phases.

    Parameters
    ----------
    weight : float, default=1.0
        A scalar multiplier applied to the computed loss value to control its 
        relative importance in multi-objective optimization.
    """
    
    # ===========

    # -- __init__
    def __init__(self, weight: float = 1.0):
        """
        Initializes the base loss module with a specific weight.
        """
        # ------------------------------------------------

        super().__init__()
        self.weight = weight
        
        debug_logger.debug(f"BaseLoss initialized with weight: {weight}")


    # -- forward
    @abstractmethod
    def forward(self, prediction, target, **kwargs):
        """
        Abstract method defining the standard loss computation interface.

        Parameters
        ----------
        prediction : torch.Tensor
            The output generated by the model.
        target : torch.Tensor
            The ground truth or reference data.
        **kwargs : Any
            Additional metadata or tensors required for specific loss variants.

        Returns
        -------
        torch.Tensor
            The calculated loss scalar or map.
        """
        # ------------------------------------------------
        pass


    # -- apply_weight
    def apply_weight(self, loss):
        """
        Applies the internal scalar weight to a computed loss value.

        Parameters
        ----------
        loss : torch.Tensor
            The raw loss value prior to weighting.

        Returns
        -------
        torch.Tensor
            The weighted loss value.
        """
        # ------------------------------------------------
        
        weighted_loss = loss * self.weight
        debug_logger.debug(f"Applied weight {self.weight} to loss.")
        
        return weighted_loss
    

# == WeightedSumLoss ==
class WeightedSumLoss(BaseLoss):
    """
    Generic container to aggregate multiple loss functions into a single objective.

    Computes a weighted linear combination of multiple criteria: 
    $$L_{total} = sum w_i cdot L_i$$

    Parameters
    ----------
    losses : List[nn.Module]
        A list of initialized loss modules to be summed.
    weights : List[float]
        A list of weights corresponding to each loss function in the aggregate.
    global_weight : float, default=1.0
        A global scalar multiplier applied to the final aggregated sum.
    """
    
    # ===========

    # -- __init__
    def __init__(self, losses: List[nn.Module], weights: List[float], global_weight: float = 1.0):
        """
        Initializes the weighted sum aggregator.
        """
        # ------------------------------------------------

        super().__init__(global_weight)
        
        assert len(losses) == len(weights), "Number of losses and weights must match."
        
        self.losses = nn.ModuleList(losses)
        self.weights = weights
        
        debug_logger.debug(f"WeightedSumLoss initialized with {len(losses)} sub-losses.")


    # -- forward
    def forward(self, prediction, target, **kwargs):
        """
        Computes the weighted sum of all registered loss functions.

        Parameters
        ----------
        prediction : torch.Tensor
            The output generated by the model.
        target : torch.Tensor
            The ground truth or reference data.
        **kwargs : Any
            Additional metadata or tensors passed to sub-losses.

        Returns
        -------
        torch.Tensor
            The aggregated weighted loss value.
        """
        # ------------------------------------------------

        total_loss = 0.0
        
        for loss_fn, w in zip(self.losses, self.weights):
            debug_logger.debug(f"Computing sub-loss: {loss_fn.__class__.__name__} with local weight: {w}")
            
            step_input = prediction
            
            # --- SMART DISPATCH LOGIC ---
            if isinstance(prediction, dict):
                loss_name = loss_fn.__class__.__name__
                
                # Case A: Phase Regularizers need the DICT (to find 'phase_maps')
                if "Phase" in loss_name or "TV" in loss_name or "Align" in loss_name:
                    step_input = prediction
                
                # Case B: Standard Losses (L1, Dice, CE) need the TENSOR
                else:
                    # Priority extraction of the main prediction tensor
                    step_input = prediction.get("pred", 
                                 prediction.get("reconstruction", 
                                 prediction.get("segmentation", 
                                 next(iter(prediction.values()))))) # Fallback
                    
            # Individual losses already apply their own global weights, 
            # but here we apply the composition weight 'w'
            total_loss += w * loss_fn(step_input, target, **kwargs)
            
        debug_logger.debug("Aggregated WeightedSumLoss computation complete.")
        
        return self.apply_weight(total_loss)